apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    crazy-chinese.com/created-by: "cluster-admin"
spec:
  containers:
    - name: mypp
      image: ikubernetes/myapp:v1
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: html
    - name: busybox
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /data/
          name: html
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do $(date) >> /data/index.html; sleep 2; done"
  volumes:
    - name: html
      emptyDir: {}