apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    crazy-chinese.com/created-by: "cluster-admin"
spec:
  containers:
    - name: mypp
      image: ikubernetes/myapp:v1
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: html
  volumes:
    - name: html
      hostPath:
        path: /root/learning-kubernetes/pod/volumes
        type: DirectoryOrCreate
