apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-demo
  namespace: default
spec:
  containers:
    - name: nfs-container
      image: ikubernetes/myapp:v1
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: html
  volumes:
    - name: html
      nfs:
        path: /data/nfs_volumes
        server: k8snode2