apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc01
  namespace: default # namespace as pod namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Mi
    limits:
      storage: 10Mi
  selector:
    matchLabels:
      name: pv01

---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
  namespace: default
spec:
  containers:
    - name: myapp
      image: ikubernetes/myapp:v1
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: nfs-pvc01